// 모듈화된 스타일 시스템
// 기존 코드와의 호환성을 위해 모든 스타일을 re-export

export {
  WIN95_COLORS,
  COMMON_STYLES,
  ROOM_CONTROL_CONSTANTS,
  ROOM_CONTROL_STYLES,
  SLIDER_THUMB_CSS,
  CONTAINER_STYLES,
  BUTTON_STYLES,
  GRID_STYLES,
  FORM_STYLES,
  COMPONENT_STYLES,
  MODAL_STYLES
} from './index' 